# Generated by Django 3.2 on 2021-04-15 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=8192)),
                ('type', models.CharField(max_length=128)),
                ('author_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=8192)),
                ('tag', models.CharField(max_length=10)),
                ('priority', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('assignee_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Assign_to', to='authentication.user')),
                ('author_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Written_by', to='authentication.user')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persmission', models.CharField(choices=[(1, 'not allowed'), (2, 'allowed')], max_length=128)),
                ('role', models.CharField(max_length=128)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=8192)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.user')),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.issue')),
            ],
        ),
    ]
