# Generated by Django 3.2 on 2021-04-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='persmission',
            new_name='permission',
        ),
    ]
