# Generated by Django 3.2 on 2021-04-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210423_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=128),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('to do', 'to do'), ('in progress', 'in progress'), ('finished', 'finished')], max_length=128),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('bug', 'bug'), ('upgrade', 'upgrade'), ('task', 'task')], max_length=128),
        ),
    ]
